### ISSUE TITLE
优化对代码块语言名称的识别

### ISSUE THREAD

**Issue by nickhoo555** [frostime/sy-run-js#1]
作者您好，
如下图，安装后已启用（顶栏菜单已出现），但是js代码块菜单无此插件。
请教一下是还有其他设置需要操作吗，感谢🙏

<img width="969" alt="image" src="https://github.com/frostime/sy-run-js/assets/25193605/dc6c8010-beed-4939-a01c-e04784b24031">

**Comment by frostime** [comment]
你把语言改成 javascript（小写） 或者 js 试试看

**Comment by frostime** [comment]
可能是因为你用的是 `Javascript` 所以没有识别出来，我后面会优化一下的

![image](https://github.com/frostime/sy-run-js/assets/27268127/c2432fb2-8d03-4de5-a0b1-617686b2c458)

**Comment by frostime** [comment]
![image](https://github.com/frostime/sy-run-js/assets/27268127/e5cee146-c942-48a8-86cf-a497e12b3021)

**Comment by frostime** [comment]
先close了，有啥问题继续在这问
