### ISSUE TITLE
createRunButton已失效，插入的按钮无法执行点击事件

### ISSUE THREAD

**Issue by wish5115** [frostime/sy-run-js#11]
createRunButton已失效，插入的按钮无法执行点击事件。

可能是因为ButtonTemplate注入的js代码给过滤掉了。

**Comment by frostime** [comment]
你好，这是因为思源这几个版本更新的时候，默认禁用了 html 块的 js 执行功能。

请在设置当中打开。

![image](https://github.com/user-attachments/assets/c16c94ac-f97c-47b8-baf1-983a489116f0)

**Comment by wish5115** [comment]
了解了，感谢大佬的指导！
