### ISSUE TITLE
功能建议：接收外部js并执行

### ISSUE THREAD

**Issue by AdachiQ** [frostime/sy-run-js#12]
功能类似这个插件https://github.com/taotaochen86/siyuan-plugin-jsrunner
这个插件有两个缺点：
1，自己起了一个server来监听固定端口，不适用于多工作空间。
2，没有引入思源的api，只能执行基本的js。

我评估了一下，在f佬你这里改比较简单，所以给你提issue😄
```javascript
const runjs = client.broadcast({"channel":"runjs"});
runjs.onmessage = (event) => {
eval(event.data);
};
```

**Comment by frostime** [comment]
你是指用思源提供的 websocket broadcast API 吗？

**Comment by AdachiQ** [comment]
> 你是指用思源提供的 websocket broadcast API 吗？
你先在代码块中运行这个：
```javascript
const runjs = client.broadcast({"channel":"runjs"});
runjs.onmessage = (event) => {
eval(event.data);
};
``` 
然后运行这个quicker动作：https://getquicker.net/Sharedaction?code=52090d65-a23a-46fd-29d6-08dccbee7fd4

大概就是这么个交互方式以及效果。

**Comment by frostime** [comment]
我大概知道你说的是哪个了。

**Comment by frostime** [comment]
channel 名称为 sy-run-js，和插件名称保持一致。
